/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JComboBox;
import javax.swing.JTextField;



/**
 *
 * @author user
 */
public class Accounts_Add extends javax.swing.JDialog {

     ResultSet rs = null;
          public String mx,sql;

        PreparedStatement pst = null;
        public String xaccno,xnam,xtyp,xgrp,xintrtyp,xgrpaccno,xgrpnam;
        static String pind,zaccno;
    /**
     * Creates new form Users_add
     */
    public Accounts_Add(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         ok.setText(pind);
        if(pind.equals("Add"))
        {
            
        }else
        {
          poputate_fields();
        }
         try {
             grpnam=Combos.accgrps(grpnam);
         } catch (SQLException ex) {
             Logger.getLogger(Accounts_Add.class.getName()).log(Level.SEVERE, null, ex);
            //  MessageBox.infoBox(ex.toString(), "Error");
         }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        grpaccno = new javax.swing.JTextField();
        grpnam = new javax.swing.JComboBox<>();
        grp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Acc No");

        jLabel2.setText("Acc Name");

        accno.setEditable(false);

        ok.setText("Save");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Class");

        jLabel4.setText("Acc group");

        jLabel7.setText("Group Code");

        grpaccno.setEditable(false);

        grpnam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                grpnamFocusLost(evt);
            }
        });
        grpnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpnamActionPerformed(evt);
            }
        });

        grp.setEditable(false);
        grp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grpnam, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grpaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(grpnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(grpaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(grp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(jButton2))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
         int mm=accno.getText().toString().length();
         if(mm!=4)
         {
             MessageBox.infoBox("Account No. Must be 4 Characters!!", "Account No");
         }
          JTextField nn[] = { accno,nam,grp};
        JComboBox zz[] = {grpnam};
        int jj = Validate_Empty_Fields.validate_textfields(nn);
        int yy = Validate_Empty_Fields.validate_comboboxes(zz);
        if (jj == 1 || yy == 1) {
            return;
        }
        
        
        
        
        getdata();   
        if(ok.getText().toString().equals("Add"))
        {
            do_add();
        }else
        {
            do_edit();
        }        
    }//GEN-LAST:event_okActionPerformed
public void do_edit()
{
        Connection conn =DBconnect.ConnecrDb();   
         //      sql = "insert into  saccodb (reg,membid,nam,grp,cat,metno,metsz,idno,telno,paddr,email,sdate,stime) values('"+xreg+"','"+xmembid+"','"+xnam+"','"+xgrp+"','"+
         //                xcat+"','"+xmetno+"','"+xmetsz+"','"+xidno+"','"+xtelno+"','"+
         //              xpaddr+"','"+xemail+"',CURDATE(),CURTIME())";
                
           sql=" update accounts set "+
                    //    "membid='" + xmembid +"'"+
                        "nam='" + xnam +"'"+
                //        ",grp='" + xgrp +"'"+
                //        ",grpaccno='" + xgrpaccno +"'"+
                //    ",grpnam='" + xgrpnam +"'"+
                     //   ",idno='" + xidno +"'"+
                     //   ",telno='" + xtelno +"'"+
                     //   ",email='" + xemail +"'"+
                    //    ",town='" + xtown +"'"+
                   //     ",paddr='" + xpaddr +"'"+
                        "  where accno='"+zaccno+"'";  
         System.out.println(sql);
          try {
             
              
              pst=conn.prepareStatement(sql);
              pst.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Users_add.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox(ex.toString(), "Edit Account");
              return;
         //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
          }
           MessageBox.infoBox("Record "+pind+"ed Successfully", pind+" Account");
}
    public void do_add()
{
     Connection conn =DBconnect.ConnecrDb();   
               sql = "insert into  accounts (accno,nam,grpaccno,grpnam,grp,sdate,stime) values"
                       + "('"+xaccno+"','"+xnam+"','"+xgrpaccno+"','"+xgrpnam+"','"+xgrp+"',CURDATE(),CURTIME())";
                
         
         System.out.println(sql);
          try {
             
              
              pst=conn.prepareStatement(sql);
              pst.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Users_add.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox(ex.toString(), "Add Account");
              return;
         //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
          }
     accno.setText("");
     nam.setText("");
      grpaccno.setText("");
    // typ.setSelectedItem("");
     grp.setText("");
     grpnam.setSelectedItem("");
     grpnam.requestFocus();
 //  msbbox.show(Alert.AlertType.ERROR, "New record saved successfully","New Record" ,"ffff");       
   // Members_listController zn = new Members_listController();
   MessageBox.infoBox("Account Created Successfully", "Add Account");
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Accounts_Add.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void grpnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpnamActionPerformed
        // TODO add your handling code here:
        
       do_grp();
    }//GEN-LAST:event_grpnamActionPerformed

    private void grpnamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grpnamFocusLost
        // TODO add your handling code here:
        do_grp();
    }//GEN-LAST:event_grpnamFocusLost

    private void grpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grpActionPerformed
    public void do_grp() {
        Connection conn = DBconnect.ConnecrDb();

        sql = "SELECT * from accountsgrp where nam='" + grpnam.getSelectedItem().toString() + "'";

        try {
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            while (rs.next()) {
                grpaccno.setText(rs.getString("accno"));
                 grp.setText(rs.getString("grp"));
                getlastno(rs.getString("accno"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
            // MessageBox.infoBox(ex.toString(), "Error");
        }
    }
    
    public void getlastno(String xc) {
        Connection conn = DBconnect.ConnecrDb();

        sql = "SELECT count(*) as cnt from accounts where grpaccno='" + xc +"'";
         int cnt=0;
        try {
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            while (rs.next()) {
                cnt =Integer.parseInt( rs.getString("cnt"));
              //  getlastno(rs.getString("accno"));
            }
           int acc=Integer.parseInt(xc);
          acc=acc+cnt+1;
          accno.setText(Integer.toString(acc));
          nam.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
            // MessageBox.infoBox(ex.toString(), "Error");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Users_add dialog = new Users_add(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void getdata()
{
    //membid 	payid 	nam 	toe 	idno 	telno 	email 	paddr 	town 	sdate 	stime 	ldate 	ltime 
    xaccno=accno.getText().toString();
   // xpayid=payid.getText().toString();
    xnam=nam.getText().toString();
    xgrpaccno=grpaccno.getText().toString();
  //  xdur=dur.getText().toString();
   // xtyp=typ.getSelectedItem().toString();
    xgrp=grp.getText().toString();
    xgrpnam=grpnam.getSelectedItem().toString();
 //   xemail=email.getText().toString();
 //   xtelno=telno.getText().toString();
 //   xpaddr=paddr.getText().toString();
 //   xtown=town.getText().toString();
   // xmembid=membid.getText().toString();
  // ActionEvent event = null;
  
         // zn = new Members_listController;
   
}
    
public void poputate_fields()
    {
         Connection conn =DBconnect.ConnecrDb();   
     
           sql = "SELECT * from accounts where accno='"+zaccno+"'";

        try {
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            rs.first();
        //    town.setSelectedItem(rs.getString("town"));
            accno.setText(rs.getString("accno"));
            nam.setText(rs.getString("nam"));
            grpaccno.setText(rs.getString("grpaccno"));
            //.setSelectedItem(rs.getString("grp"));
            grp.setText(rs.getString("grp"));
             grpnam.setSelectedItem(rs.getString("grpnam"));
        //     typ.setSelectedItem(rs.getString("typ"));
        
         //   plotno.setText(rs.getString("plotno"));

        } catch (SQLException ex) {
            Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
        }

   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JTextField grp;
    private javax.swing.JTextField grpaccno;
    private javax.swing.JComboBox<String> grpnam;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nam;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
