/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import static kiwacoe.Login.user;

/**
 *
 * @author user
 */
public class Debits_B_add extends javax.swing.JDialog {

     ResultSet rs = null;
          public String mx,sql;

        PreparedStatement pst = null;
        public String xuserid,xyr,xmon,xtyp; 
    /**
     * Creates new form Users_add
     */
    public Debits_B_add(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mon = new javax.swing.JComboBox<>();
        yr = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        typ = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Month");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 48, 80, -1));

        jLabel2.setText("Year");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 83, -1, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 194, -1, -1));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 194, -1, -1));

        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 45, 106, -1));

        yr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        getContentPane().add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 83, 106, -1));

        jLabel3.setText("Batch Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 126, 72, -1));

        typ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debits", "Credits" }));
        typ.setToolTipText("");
        getContentPane().add(typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 123, 106, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ind=0;
        getdata();   
         try {
           ind=  ifexists();
         } catch (SQLException ex) {
             Logger.getLogger(Payments_B_add.class.getName()).log(Level.SEVERE, null, ex);
         }
         if (ind>0)
         {
           MessageBox.infoBox("Batch Already Exists", "Create Batch");
           return;
         }
       Connection conn =DBconnect.ConnecrDb();   
               sql = "insert into  drbatches (yr,mon,typ,recs,stat,bdate) values('"+xyr+"','"+xmon+"','"+xtyp+"',0,'Open',CURDATE())";
                
         
         System.out.println(sql);
          try {
             
              
              pst=conn.prepareStatement(sql);
              pst.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Users_add.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox(ex.toString(), "Add User");
              return;
         //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
          }

 //  msbbox.show(Alert.AlertType.ERROR, "New record saved successfully","New Record" ,"ffff");       
   // Members_listController zn = new Members_listController();
   MessageBox.infoBox("User Created Successfully", "Add User");
   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Debits_B_add.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Users_add dialog = new Users_add(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void getdata()
{
    
    xyr=yr.getSelectedItem().toString();
    xmon = String.format("%02d", mon.getSelectedIndex() + 1);
    xtyp=typ.getSelectedItem().toString();

   
}

 public int ifexists() throws SQLException 
 {
     int x = 0;
     String sql = "SELECT yr,mon,typ,COUNT(*) as count FROM drbatches  where yr='" + xyr + "' and mon='" + xmon + "' and typ='" + xtyp + "'  group by yr,mon,typ";
     Connection connx = DBconnect.ConnecrDb();
     pst = connx.prepareStatement(sql);

     rs = pst.executeQuery();
     //rs.first();
     while (rs.next()) {
        // user = rs.getString("userid");
       //  pwd = rs.getString("pass");
      //   typ = rs.getString("typ");
         x = Integer.valueOf(rs.getString("count"));
     }

     return x;
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JComboBox<String> typ;
    private javax.swing.JComboBox<String> yr;
    // End of variables declaration//GEN-END:variables
}
