/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

//import static examples.NewJFrame2.pst;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static kiwacoe.Loan_Repay_Capture.sql;


//217101008070
//import static majiApp.Payments_capture.zyr;
//import static majiApp.Payments_capture.pst2;
//import static majiApp.Payments_BList.zstat;
//import static majiApp.Payments_capture.sql;
//import static majiApp.Payments_capture.zmon;

/**
 *
 * @author user
 */
public class Expenses_Capture extends javax.swing.JFrame {
    static ResultSet rs = null;
    int ff = 0;
    static ResultSet rs2 = null;
    static ResultSet rs3 = null;
    static String mx, sql, xseq;
    public int x = 0, r = 0;
    double tamt = 0;
    int cnt = 0;
    static PreparedStatement pst = null;
    static PreparedStatement pst2 = null;
    static PreparedStatement pst3 = null;
    //xmembid+"','"+xnam+"',"+xamt+",'"+xtyp+"','"+xcomm+"','"+xyr+"','"+xmon+"
    public String xnam, xamt, xcomm, xtyp, xaccno, xrdate, xdocno;
    static String zyr, zmon, ztyp, zfind, zstat;
    public Connection conn = DBconnect.ConnecrDb();

    /**
     * Creates new form NewJDialog
     */
    public Expenses_Capture(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
        jTable1=SetTable.data(jTable1);
         jButton3.setText("Add");
        zmon = Expenses_List.zmon;
        zyr = Expenses_List.zyr;
    //    ztyp = Expenses_Capture.ztyp;
      //  zreg = Readings_BList.zreg;
        zstat = Expenses_List.zstat;
       
       doread();
      jLabel7.setText("Year:  " + zyr + "    Month: " + zmon  +"  Status:  "+zstat);
       seq.setVisible(false);
       nam.setEditable(false);
         if (zstat.equals("Posted"))
        {
          jButton3.setVisible(false);
            
        }
             ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String muserid = null;
                String mtyp = null;
                String mnam = null;
                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();
                int row = jTable1.getSelectedRow();
                int col = 1; // ID is the first Column
                
              if (row>-1)
                {    
                seq.setText(jTable1.getValueAt(row, 0).toString());
                 docno.setText(jTable1.getValueAt(row, 1).toString());
                 accno.setText(jTable1.getValueAt(row, 2).toString());
               nam.setText(jTable1.getValueAt(row, 3).toString());
               amt.setText(Format_amt.uformat( jTable1.getValueAt(row, 4).toString()));
               typ.setSelectedItem(jTable1.getValueAt(row, 5).toString());
               comm.setText(jTable1.getValueAt(row, 6).toString());
              //  membid.setText(jTable1.getValueAt(row, 5).toString());
                 rdate.setText(Format_date.dmy( jTable1.getValueAt(row, 7).toString()));
                                 
               jButton3.setText("Save");
                               System.out.println("Selected: " + mtyp);
                }
            }

        });
         jButton1.setVisible(false);
         jButton2.setVisible(false);
          cmt.setVisible(false);
          updatetots();
       // poputate_fields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nam = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comm = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        seq = new javax.swing.JTextField();
        accno = new javax.swing.JTextField();
        rdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typ = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        docno = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lcnt = new javax.swing.JLabel();
        ycr = new javax.swing.JTextField();
        bal = new javax.swing.JTextField();
        ydr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 557, 244, -1));

        jLabel1.setText("Acc No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 456, 108, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 497, 108, -1));

        cmt.setFocusable(false);
        getContentPane().add(cmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 225, -1));

        jLabel5.setText("Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 567, 100, -1));

        jButton1.setText(">>");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        jButton2.setText("<<");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 599, 100, -1));

        jButton4.setText("Close");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 599, 90, -1));

        nam.setFocusable(false);
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });
        getContentPane().add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 494, 244, -1));

        add.setText("New");
        add.setFocusable(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jLabel6.setText("Remarks");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 417, 100, -1));

        comm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commActionPerformed(evt);
            }
        });
        getContentPane().add(comm, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 417, 240, -1));

        jButton5.setText("Find");
        jButton5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton5FocusGained(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 457, 60, -1));

        jLabel8.setText("Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 382, 86, -1));

        seq.setText("jTextField1");
        getContentPane().add(seq, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 599, -1, -1));

        accno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accnoFocusLost(evt);
            }
        });
        getContentPane().add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 457, 169, -1));

        rdate.setEditable(false);
        getContentPane().add(rdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 383, 172, -1));

        jLabel3.setText("Transaction Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 527, 100, -1));

        typ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Credit", "Debit" }));
        typ.setToolTipText("");
        getContentPane().add(typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 527, 244, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 400, 270, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 599, 190, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, 403, 28));

        jLabel9.setText("Ref No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 351, 100, -1));

        docno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docnoActionPerformed(evt);
            }
        });
        getContentPane().add(docno, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 347, 170, -1));

        jButton6.setText("#");
        jButton6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton6FocusGained(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 382, 61, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 818, 223));

        lcnt.setText(" ");
        getContentPane().add(lcnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 366, 156, 23));

        ycr.setEditable(false);
        ycr.setBackground(new java.awt.Color(51, 255, 204));
        ycr.setFocusable(false);
        getContentPane().add(ycr, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 206, -1));

        bal.setEditable(false);
        bal.setBackground(new java.awt.Color(51, 255, 204));
        bal.setFocusable(false);
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 206, -1));

        ydr.setEditable(false);
        ydr.setBackground(new java.awt.Color(51, 255, 204));
        ydr.setFocusable(false);
        getContentPane().add(ydr, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 435, 206, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

          try{
            if (x == 0) {
                open();
            }

            if(!rs3.isLast())
            {
                rs3.next();
                int cnt= rs3.getRow();
                int cmm=  cntt();
                cmt.setText(Integer.toString( cnt)+" of "+ Integer.toString( cmm));
                loaddata();
            }else
            {
                rs3.last();
                //   msbbox.show( Alert.AlertType.ERROR,"End of File", "titleBar",  "Header");
                return;
            }
        } catch (SQLException ex) {
            //      Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
public void doread()
{
 
  
    sql = " select * from  expenses where CONCAT( yr,mon)='"+zyr+zmon+"'";
 

    System.out.println(sql);
    DefaultTableModel model = new DefaultTableModel();
    // jTable1 hh;
    jTable1.setModel(model);

    model.addColumn("Rec ID");
    model.addColumn("Ref No");
      model.addColumn("Acc No");
    model.addColumn("Name");
   
    model.addColumn("Amount");
     model.addColumn("Type");
    model.addColumn("Remarks");

    model.addColumn("Date");

    //   model.addColumn("2 Name");
    Connection conn = DBconnect.ConnecrDb();

    int cnt = 0;
    double tamt = 0;
    double cr = 0;
    double dr = 0;
     double damt=0;
    try {
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        // rs.first();
        int p = 0;
        while (rs.next()) {
            //  readdata();
            if( rs.getString("typ").equals("Debit"))
            {
                damt=Double.parseDouble(rs.getString("amt"));
                  dr=dr+Double.parseDouble(rs.getString("amt"));
            }   else
            {
                 damt=0-Double.parseDouble(rs.getString("amt"));
                   cr=cr+Double.parseDouble(rs.getString("amt"));
            }
           
            cnt = cnt + 1;
            tamt = tamt + damt;
            model.insertRow(p, new Object[]{
                rs.getString("seq"),
                rs.getString("docno"),
                rs.getString("accno"),
                rs.getString("nam"),
               
                Format_amt.format(rs.getString("amt")),
                 rs.getString("typ"),
                //         rs.getString("dur"),
                rs.getString("comm"),
                rs.getString("rdate"),});
        }
    } catch (SQLException ex) {
        Logger.getLogger(UsersLIst.class.getName()).log(Level.SEVERE, null, ex);
    }
    lcnt.setText("Record Count = " + Integer.toString(cnt));
    ydr.setText("Total Debit = " + Format_amt.format(Double.toString(dr)));
    ycr.setText("Total Credit = " + Format_amt.format(Double.toString(cr)));
    bal.setText("Total Balance = " + Format_amt.format(Double.toString(tamt)));
    jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ALL_COLUMNS);
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
    //  jTable1.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
    jTable1.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  try {
            if (x == 0) {
                open();
            }

            if (!rs3.isFirst()) {
                rs3.previous();
                int cnt= rs3.getRow();

                int cmm=  cntt();
                cmt.setText(Integer.toString( cnt)+" of "+ Integer.toString( cmm)  );
                // String tmembid = rs.getString("membid");  //+"\n";
                loaddata();
            } else {
                // msbbox.show(Alert.AlertType.ERROR, "End of File", "titleBar", "Header");
                rs3.first();
                loaddata();
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
           JTextField nn[] = { accno,nam,amt,comm,rdate,docno};
        JComboBox zz[] = {typ};
        int jj = Validate_Empty_Fields.validate_textfields(nn);
      //  int yy = Validate_Empty_Fields.validate_comboboxes(zz);
        if (jj == 1 ) {
            return;
        }
          getdata();   
        String mm=jButton3.getText().toString();
        if (mm.equals("Save"))
        {
            performSave();
           
        }else
        {
            performAdd();
           // doread();
        }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       // NewJFrame2 frame = new NewJFrame2();

       // frame.dispose();
        Expenses_Capture.this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed
public void updatetots()
{
     try {
              PreparedStatement pst7 = null; 
              Connection connx=DBconnect.ConnecrDb();
              String sql4="update shbatches set recs="+cnt+",tot="+tamt+" where CONCAT(yr,mon,typ)='"+zyr+zmon+ztyp+"'";
              System.out.print(sql4);
            //  MessageBox.infoBox(sql4, zstat);
              pst7=connx.prepareStatement(sql4);
              pst7.executeUpdate(sql4);
             
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Shares_Capture.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox(ex.toString(), "New  Batch");
              return;
         //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
          }
}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     updatetots();
     
       if(zstat.equals("Posted"))
       {
           MessageBox.infoBox("Batch Alread Posted!!", "Add Record");
           return;
       }
     x=0;
         accno.setText( "");
         
         nam.setText( "");
         //   typ.setSelectedItem( "");
         amt.setText( "");
         rdate.setText( "");
         comm.setText( "");
           docno.setText( "");
         jButton3.setText("Add");
         jButton3.setEnabled(true);
         docno.requestFocus();
    }//GEN-LAST:event_addActionPerformed

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtActionPerformed

    private void commActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         ff=1;
        //  zmembid="";
       //   znam="";
          Find_Account.zfind="Accounts";
        Find_Account dd=new Find_Account();
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
               dd.setResizable(false);
          dd.setTitle("Find Account");
          dd.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void accnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accnoFocusLost
        // TODO add your handling code here:
          if(zstat.equals("Posted"))
       {
        //   MessageBox.infoBox("Batch Alread Posted!!", "Add Record");
           return;
       }
           if (accno.getText().trim().isEmpty())
           {
               jButton3.setEnabled(false);
                jButton3.setEnabled(true);
           }else
           {
                jButton3.setEnabled(true);
                //  jButton3.setEnabled(false);
               try {
                   populate_data();
               } catch (SQLException ex) {
                   Logger.getLogger(Expenses_Capture.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
                   
    }//GEN-LAST:event_accnoFocusLost

    private void jButton5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton5FocusGained
        // TODO add your handling code here:
        if  ( ff==0)
      {
          
      }else
      {
        if (zstat.equals("Open"))
        {
            //  MessageBox.infoBox(Find_Customer.zmembid, zstat);
            accno.setText(Find_Account.zaccno);
            nam.setText(Find_Account.znam);
            typ.requestFocus();
            ff=0;
        }
      }
    }//GEN-LAST:event_jButton5FocusGained

    private void docnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docnoActionPerformed

    private void jButton6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton6FocusGained
        // TODO add your handling code here:
        if (r ==1 && Kalenda.gdat.length()>0) {
            r=0;
            rdate.setText( Kalenda.gdat);
            accno.requestFocus();
        }else
        {
            r=0;
        }
    }//GEN-LAST:event_jButton6FocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        r=1;
        Kalenda dd=new Kalenda();
        // dd.setModal(true);
        //  dialog.setSize(400, 400);
        dd.setLocationRelativeTo(null);
        // dd.setExtendedState(dd.MAXIMIZED_BOTH);
        dd.setDefaultCloseOperation(dd.DO_NOTHING_ON_CLOSE);
        dd.getContentPane().setBackground(Color.decode("123130040"));
        dd.setResizable(false);
        dd.setTitle("Calender");
        dd.setVisible(true);

        //  MessageBox.infoBox(Kalenda.gdat, user);
        //  this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

   public void populate_data() throws SQLException
{
     String sql = "SELECT *  from accounts where accno='"+accno.getText().toString()+"'";
    //Connection conn = DBconnect.ConnecrDb();
    System.out.println(sql);
    pst2 = conn.prepareStatement(sql);
    rs2 = pst2.executeQuery();
   // metno="Nil";
   // metsz="Nil";
    while(rs2.next())
    {
        nam.setText(rs2.getString("nam"));
    
    typ.requestFocus();
        
    }
  
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payments_capture dialog = new Payments_capture(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
               
              //  dialog.setModal(true);
              //  dialog.setSize(400, 400);
                dialog.setLocationRelativeTo(null);
                 dialog.setTitle("Shares");
                 dialog.setResizable(false);
                dialog.setVisible(true);
            }
        });
    }
public void open() throws SQLException
{
    String        sql = "SELECT * from expenses where yr='" + zyr + "' and mon='" + zmon + "'";
  //  Connection conn = DBconnect.ConnecrDb();
    pst3 = conn.prepareStatement(sql);
    rs3 = pst3.executeQuery();
    x = 1;    
    int cnt= cntt();
   cmt.setText(Integer.toString( cnt));
}
public void loaddata()
{
      try {
          
        String mdate[] = rs3.getString("rdate").split("-");
            String yy = mdate[0];
            String mm = mdate[1];
            String dd = mdate[2];
            rdate.setText(dd + "/" + mm + "/" + yy);
        accno.setText(rs3.getString("accno"));

        nam.setText(rs3.getString("nam"));
        
       // rdate.setText(rs3.getString("rdate"));
        amt.setText(rs3.getString("amt"));
      //  pread.setText(rs3.getString("pread"));
      //  cread.setText(rs3.getString("cread"));
        comm.setText(rs3.getString("comm"));
        docno.setText(rs3.getString("docno"));
         seq.setText(rs3.getString("seq"));
           typ.setSelectedItem(rs3.getString("typ"));
        jButton3.setText("Save");

    } catch (SQLException ex) {
        Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
       MessageBox.infoBox(ex.toString(), "dd");
    }

}
public void performAdd()
{
    
    
   //  String dd=xrdate.substring(0,2);
  //   String ddx=xrdate.substring(0,5);
  //   String mm=ddx.substring(3);
    
 //    String yy=xrdate.substring(6);
 //    xrdate=yy+"/"+ mm+"/"+dd;
//  MessageBox.infoBox(xrdate, "sss");// membid,nam,typ,grp,comm,yr,mon,reg,cread,pread,cdate,ctime                                     
       sql = "insert into  expenses (accno,nam,typ,amt,comm,docno,yr,mon,rdate,cdate,ctime,stat)"
               + " values('"+xaccno+"','"+xnam+"','"+xtyp+"',"+xamt+",'"+xcomm+"','"+xdocno+"','"+zyr+"','"+zmon+"','"+xrdate+"',CURDATE(),CURTIME(),'U')";  
    //   Connection conn=DBconnect.ConnecrDb();
         System.out.println(xrdate);
          try {
             
              
              pst2=conn.prepareStatement(sql);
              pst2.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
               msbbox.show(Alert.AlertType.ERROR, ex.toString(),"insertrec Method" ,"Database Error");
               return;
          }
     updatetots();
    
           nam.setText("");
          accno.setText("");
        //  grp.setText("");
       //    cat.setText("");
        //  rdate.setText("");
          amt.setText("");
        //  comm.setText("");
          accno.requestFocus();
       //   docno.set
           doread();
    
}
 public void poputate_fields() {
     //   Connection conn = DBconnect.ConnecrDb();

        sql = "SELECT * from exnpenses where yr='" + zyr + "' and mon='" + zmon  + "' and typ='" + ztyp + "'";
        
        try {
            pst = conn.prepareStatement(sql);
 
            rs = pst.executeQuery();
            rs.first();
            
            String mdate[] = rs.getString("rdate").split("-");
            String yy = mdate[0];
            String mm = mdate[1];
            String dd = mdate[2];
            rdate.setText(dd + "/" + mm + "/" + yy);
            
           // rdate.setText(rs.getString("rdate"));
            accno.setText(rs.getString("accno"));
            nam.setText(rs.getString("nam"));
              docno.setText(rs.getString("docno"));

            amt.setText(rs.getString("amt"));
             typ.setSelectedItem(rs.getString("typ"));

        } catch (SQLException ex) {
            Logger.getLogger(UsersLIst.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public void performSave()
{
    
   
     sql = " update expenses set "
            + "rdate='" + xrdate + "'"
            + ",nam='" + nam.getText().toString() + "'"
         //    + ",typ='" + nam.getText().toString() + "'"
            + ",accno='" + accno.getText().toString() + "'"
            + ",comm='" + comm.getText().toString() + "'"
            + ",docno='" + docno.getText().toString() + "'"
            + ",typ='" + typ.getSelectedItem().toString() + "'"
       
            + ",amt=" + amt.getText().toString()  + ""
     
            + //  ",paddr='" + xpaddr +"'"+
            "  where seq=" + seq.getText().toString() + "";
       
    System.out.println(sql);
     
   //   msbbox.show(Alert.AlertType.ERROR, sql,"insertrec Method" ,"Database Error");
       
         System.out.println(sql);
          try {
              pst2=conn.prepareStatement(sql);
              pst2.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox("Record Update Error", "Error");
             //msbbox.show(Alert.AlertType.ERROR, ex.toString(),"insertrec Method" ,"Database Error");
              return;
          }
       
     try {
         refresh_recordset(); //msbbox.show(Alert.AlertType.ERROR, ex.toString(),"insertrec Method" ,"Database Error");
     } catch (SQLException ex) {
         Logger.getLogger(Expenses_Capture.class.getName()).log(Level.SEVERE, null, ex);
     }
      doread();
}
public void refresh_recordset() throws SQLException 
{
   
}
public void getdata()
{
    
        xaccno = accno.getText().toString();
        xnam = nam.getText().toString();
         xrdate = rdate.getText().toString();
      //   xrdate = rdate.getText().toString();
    xrdate = xrdate.replace("-", "/");
    String mdate[] = xrdate.split("/");
    String d = mdate[0];
    String m = mdate[1];
    String y = mdate[2];
    xrdate = y + "-" + m + "-" + d;
        xamt = amt.getText().toString();
        xcomm = comm.getText().toString();
         xdocno = docno.getText().toString();
       xtyp = typ.getSelectedItem().toString();
}
public int cntt() throws SQLException
{
    
    String sql = "SELECT count(*) as cnt from expenses ";
  //  Connection conn = DBconnect.ConnecrDb();
    System.out.println(sql);
    pst2 = conn.prepareStatement(sql);
    rs2 = pst2.executeQuery();
    rs2.next();
    int cnt= rs2.getInt("cnt");
    return cnt;
}
public Date convertToDate(String receivedDate) throws ParseException{
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        Date date = formatter.parse(receivedDate);
        return date;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JButton add;
    private javax.swing.JTextField amt;
    private javax.swing.JTextField bal;
    private javax.swing.JTextField cmt;
    private javax.swing.JTextField comm;
    private javax.swing.JTextField docno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lcnt;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField rdate;
    private javax.swing.JTextField seq;
    private javax.swing.JComboBox<String> typ;
    private javax.swing.JTextField ycr;
    private javax.swing.JTextField ydr;
    // End of variables declaration//GEN-END:variables
}
