/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

//import static majiApp.Readings_BList.zyr;


/**
 *
 * @author user
 */
public class Expenses_List extends javax.swing.JFrame {
DefaultTableModel testlist = new DefaultTableModel();
 ResultSet rs = null;
  ResultSet rs2 = null;
          public String mx,sql;
     HashMap hm=   null;
    ResultSet rs22 = null;
        PreparedStatement pst = null;
         PreparedStatement pst2 = null;
         PreparedStatement pst22 = null;
           PreparedStatement pst32 = null;
        public String xuserid,xnam,xpass,xtyp;
        static String zyr,zmon,ztyp,zstat;
        public Connection connz=null;
      //  static String muserid,mnam,mtyp; 
    //   public static  ListSelectionModel cellSelectionModel ;
    /**
     * Creates new form UsersLIst
     * 
     * 
     */
         static JTable table;
    public Expenses_List() {
    //  table=jTable1;
    
        initComponents();
        jMenu2.setVisible(false);
          String qym[]=  GetMonth.set_yr_mon();
      mon.setSelectedItem(qym[0]);
      yr.setSelectedItem(qym[1]);  
    //  doread();
        jTable1=SetTable.data(jTable1);
        jButton1.setVisible(false);
              ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String muserid = null;
                String mtyp = null;
                String mnam = null;
                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();
                int row = jTable1.getSelectedRow();
                int col = 1; // ID is the first Column
                if(row>-1)
                {
                zyr = jTable1.getValueAt(row, 0).toString();
                zmon = jTable1.getValueAt(row, 1).toString();
                zstat = jTable1.getValueAt(row, 4).toString();
                System.out.println("Selected: " + mtyp);
                }
           //     ztyp = jTable1.getValueAt(row, 2).toString();
                
            }

        });
    
     // 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        yr = new javax.swing.JComboBox<>();
        mon = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Open Batch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Print Batch");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Month");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        yr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        yr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yrFocusGained(evt);
            }
        });
        yr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrActionPerformed(evt);
            }
        });

        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });

        jLabel1.setText("Year");

        jLabel2.setText("Month");

        jButton5.setText("Post  Batch");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");
        jMenu1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenu1FocusGained(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Batches");

        jMenuItem2.setText("Add Batch");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(58, 58, 58)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row<0)
        {
           MessageBox.infoBox("No Batch Selected", "Open Batch");
           return;
        }
        
        Expenses_Capture dd=new Expenses_Capture(this,true);
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
                dd.setDefaultCloseOperation(dd.DO_NOTHING_ON_CLOSE);
               dd.setResizable(false);
          dd.setTitle("Journals Capture");
          dd.setVisible(true);
           this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // UsersLisr.e
        Expenses_List.this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          int row = jTable1.getSelectedRow();
        if(row<0)
        {
           MessageBox.infoBox("No Batch Selected", "Open Batch");
           return;
        }
           this.setCursor(cursor_typ.busy());
        hm = new HashMap();
        hm.put("yr", zyr);
        hm.put("mon", zmon);
         hm.put("title", "Journals For : " +GetMonth.format(zmon)+ "  , "+zyr);
            String filename="reportexpenses.jrxml";
      String title ="Journals For : " +GetMonth.format(zmon)+ "  , "+zyr;
      RunReports.preview(filename, hm, title);
         this.setCursor(cursor_typ.notbusy());
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //  MessageBox.infoBox("sdffdfsd", "dfdfgg");
        Expenses_B_Add dd=new Expenses_B_Add(this,true);
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
               dd.setResizable(false);
          dd.setTitle("Add Journals Batch");
          dd.setVisible(true);
         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void yrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrActionPerformed
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_yrActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
          doread();
    }//GEN-LAST:event_monActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
          doread();
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   
         String ans=Confirm.YesNo("Are You Sure?", "Post Batch");
          if (ans.equals("N"))
          {
              return;
          }
         int row = jTable1.getSelectedRow();
        if (row < 0) {
            MessageBox.infoBox("No Batch Selected", "Post Batch");
            return;
        }
        if(zstat.equals("Posted"))
        {
            MessageBox.infoBox("Batch Already Posted", "Post Batch");
            return;
        }
         try {
        // TODO add your handling code here:
        if( Validate_period.validate(zyr, zmon)<1)
        {
             MessageBox.infoBox("Cant Post,Period not open!!", "Post Batch");
             return;
        }
    } catch (SQLException ex) {
        Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        int    ind =0;
        
          try {
             ind = Validate_batchstatus.validate(zyr, zmon,"expbatches");
         } catch (SQLException ex) {
             Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
             MessageBox.infoBox(ex.toString(), "Error");
             return;
         }

        if (ind <1) 
        {
             MessageBox.infoBox("Can't Post, Batch is already posted "+Integer.toString(ind), "Post Batch");
            return;
        }
        
        
        int s=0;
        double dr=0;
        double cr=0;
        try {
            s = Validate_Expenses_Totals.validate(zyr, zmon);

             dr = Validate_Expenses_Totals.dramt(zyr, zmon);
             cr = Validate_Expenses_Totals.cramt(zyr, zmon);
        } catch (SQLException ex) {
            Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
        }
      double bal =dr-cr;
      String sbal=Double.toString(bal);
       String sdr=Double.toString(dr);
       String scr=Double.toString(cr);
      sbal=Format_amt.format(sbal);
       sdr=Format_amt.format(sdr);
        scr=Format_amt.format(scr);
      if (s==1)
      {
        MessageBox.infoBox("Batch out of balance of Ksh "+sbal+ "   : Debit="+sdr+"  Credits="+scr,"Batch Error");  
         return;
      }
         
         int t = 0;
        try {
           t =Validate_batch.validate(zyr, zmon, "expbatches");
        } catch (SQLException ex) {
            Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
       
        
        
         try {
              this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                 postbatch(zyr,zmon);
                // doread();
                  this.setCursor(Cursor.getDefaultCursor());
             } catch (SQLException ex) {
                 Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
             }
         
           
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Expenses_List.this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenu1FocusGained
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_jMenu1FocusGained

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Expenses_B_Add dd=new Expenses_B_Add(this,true);
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
                dd.setDefaultCloseOperation(dd.DO_NOTHING_ON_CLOSE);
               dd.setResizable(false);
          dd.setTitle("Add Journals Batch");
          dd.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void yrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yrFocusGained
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_yrFocusGained
  public void dopost() throws SQLException
    {
         String  sql = "SELECT * from payments where yr='" + zyr + "' and mon='" + zmon + "'  and typ='" + ztyp + "' and stat='U'";
     connz = DBconnect.ConnecrDb();
    System.out.println(sql);
    pst22 = connz.prepareStatement(sql);
    rs22 = pst22.executeQuery();
    
   
        String sql2 = "";
        String sql3 = "";
        String kmembid = "";
        String knam = "";
        String ktyp = "";
        String kdescr = "";
        String kdat = "";
        String kamt = "";
        String kdrcr = "";
        String ksoc = "";
        String kseq = "";
        int cnt=0;
        while (rs22.next()) {
            cnt=cnt+1;
            kmembid = rs22.getString("membid");
            knam = rs22.getString("nam");
          //  ktyp = rs22.getString("typ");
            kdescr = "Payment for "+zmon+" "+zyr;//rs22.getString("descr");
            kdat = rs22.getString("rdate");

            kamt = rs22.getString("amt");
            kdrcr = "Credit";
            ksoc ="Payment";
            kseq = rs22.getString("seq");
            sql2 = "insert into  caccounts (membid,nam,descr,yr,mon,reg,dat,amt,drcr,pdate,ptime,soc,pseq)"
                    + " values('" + kmembid + "','" + knam + "','"  + kdescr + "','"  + zyr +"','" + zmon + "','Nil','" + kdat + "'," + kamt + ",'" + kdrcr + "',CURDATE(),CURTIME(),'Payment',"+kseq+")";
             System.out.println(sql2);
           //  MessageBox.infoBox(sql2.toString(),"sds");
            insert_rec(sql2);
            sql3="update payments set stat='P',pdate=CURDATE(),ptime=CURTIME() where seq="+kseq;
            System.out.println(sql3);
            update_rec_stat(sql3);
        }
         sql3 = "update pybatches set stat='Posted' where CONCAT(yr,mon,typ)='" + zyr + zmon +  ztyp+"'";
        System.out.println(sql3);
         update_batch_stat(sql3);
       
        MessageBox.infoBox(Integer.toString(cnt)+ "  Records Posted Successfully", "Post");
    }
    public void update_batch2(String gyr, String gmon) throws SQLException
  {
      
      Connection conn = DBconnect.ConnecrDb();

      String sql = "SELECT count(*) as cnt from expenses where CONCAT(yr,mon)='" + gyr + gmon + "'";
      System.out.print(sql);
      int bb = 0;
      pst = conn.prepareStatement(sql);

      rs = pst.executeQuery();
      while (rs.next()) {
          bb = rs.getInt("cnt");
      }
      
      String sql2 = " update expbatches set recs=" + Double.toString(bb) + " where CONCAT(yr,mon)='" + gyr + gmon + "'";
      System.out.print(sql2);
      pst = conn.prepareStatement(sql2);
      pst.executeUpdate(sql2);
  }
     public void update_batch_stat(String ssql3)
   {
        try {
             
              
              pst32=connz.prepareStatement(ssql3);
              pst32.executeUpdate(ssql3);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Payments_BList.class.getName()).log(Level.SEVERE, null, ex);
               MessageBox.infoBox(ex.toString(),"Update Batch Status Method" );
               return;
          }
   }
   public void update_rec_stat(String ssql3)
   {
        try {
             
              
              pst32=connz.prepareStatement(ssql3);
              pst32.executeUpdate(ssql3);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Payments_BList.class.getName()).log(Level.SEVERE, null, ex);
               MessageBox.infoBox(ex.toString(),"Update Status Method" );
               return;
          }
   }
    public void insert_rec(String wsql)
    {
        try {
             
              
              pst32=connz.prepareStatement(wsql);
              pst32.executeUpdate(wsql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Payments_BList.class.getName()).log(Level.SEVERE, null, ex);
                MessageBox.infoBox(ex.toString(),"insert_rec Method" );
               return;
          }
    }
    
    public void doread()
{
 
  
    String syr = yr.getSelectedItem().toString();
    String smon = String.format("%02d", mon.getSelectedIndex() + 1);
    try {
        //  String sval=val.getText().toString();
        update_batch2(syr,smon);
    } catch (SQLException ex) {
        Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    sql = " select * from expbatches where yr='" + syr + "' and mon='" + smon + "'";
   
   
     System.out.println("qqqq"+sql);
   
    DefaultTableModel model = new DefaultTableModel();
    // jTable1 hh;
    jTable1.setModel(model);
    model.addColumn("Year");
    model.addColumn("Month");
   // model.addColumn("Region");
 //   model.addColumn("Loan Type");
    model.addColumn("No of Recs");
   
    model.addColumn("Total Amount");
     model.addColumn("stat");
    // model.
    // Create the first row
    Connection conn = DBconnect.ConnecrDb();

    //  String sql = "SELECT * from users ";

    try {
        pst = conn.prepareStatement(sql);

        rs = pst.executeQuery();
        // rs.first();
        int p = 0;
        String byr = "";
        String bmon = "";
      //  String btyp = "";
      //  String bdate = "";
        String bstat = "";
        String brecs = "";
        String btot = "";
     System.out.print("==============================================================================");
     
     while (rs.next()) {
            //  readdata();
            byr = rs.getString("yr");
            bmon = rs.getString("mon");
            //   breg = rs.getString("reg");
            //    btyp = rs.getString("typ");

            btot = rs.getString("tot");
            brecs = rs.getString("recs");
            bstat = rs.getString("stat");
            model.insertRow(p, new Object[]{byr, bmon, brecs, btot, bstat});
           //  jTable1.changeSelection(0, 0);
            jTable1.changeSelection(0, 0, false, false);
        }
    

    } catch (SQLException ex) {
        Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
        MessageBox.infoBox(ex.toString(), "Error");
    }
  //  int qqq=jTable1.getSelectedRows();
   

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersLIst().setVisible(true);
               
            }
        });
    }
  public void postbatch(String zyr,String zmon) throws SQLException
{
    
       
        //String sx = membid.getText().toString();
        sql = "SELECT * from expenses where yr='" + zyr +"' and mon='"+zmon+"'";

        Connection connx = DBconnect.ConnecrDb();

        pst2 = connx.prepareStatement(sql);
        System.out.println(sql);

        rs2 = pst2.executeQuery();
       // rs2.first();
       // readdata();
        // double cnt=0;
        while (rs2.next()) {
          //   msbbox.show(Alert.AlertType.ERROR, "post batch", "New Record", "ffff");
             readbatch(zyr,zmon);
                

        }
        Close_batch.close(zyr,zmon,"expbatches");
     //   searchz();
       MessageBox.infoBox("Posting Done!!", "Post Batch");
        
    }

 public void readbatch(String hyr,String hmon) throws SQLException {
        //accno 	loanid 	typ 	yr 	mon 	bf 	intr 	cf 	nam 
      
      
       
     String amt = rs2.getString("amt");
     String accno = rs2.getString("accno");
     String nam = rs2.getString("nam");
     String dat = rs2.getString("cdate");
     String docno = rs2.getString("docno");
     String pseq = rs2.getString("seq");
     String soc = "JE";
     String suffix = accno;
     String descr =  rs2.getString("comm");
     String dr = "0";
     String cr = "0";
      if(rs2.getString("typ").equals("Debit"))
     {
     dr=amt;
     cr = "0";
     
     }else
      {
          cr=amt;
           dr = "0";  
      }
    // String accno = accno;     
     insert_rec(docno,accno, soc, descr, suffix, dr, cr, hyr, hmon, dat, pseq);//post dr
   //  accno = "000";
    
     
   //  insert_rec(accno,soc,descr,suffix,dr,cr,hyr,hmon,dat,pseq);//post cr
         }
    
    public void insert_rec(String docno,String accno,String soc,String descr,String suffix,String dr,String cr,String hyr,String hmon,String dat,String pseq)
    {      
        sql = "insert into gl (accno,soc,descr,suffix,dr,cr,yr,mon,dat,docno,pseq,pdate,ptime) values("
                + accno
                + ",'" + soc + "'"
                + ",'" + descr + "'"
                + ",'" + suffix + "'"
                + "," + dr + ""
                + "," + cr + ""
                + ",'" + hyr + "'"
                + ",'" + hmon + "'"
                + ",'" + dat + "'"
                  + ",'" + docno + "'"
                + "," + pseq + ""
                + ",CURDATE(),CURTIME())";
         
        Connection conn = DBconnect.ConnecrDb();
        System.out.println(sql);
        try {

            pst22 = conn.prepareStatement(sql);
            pst22.executeUpdate(sql);
            //    rs= pst.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Expenses_List.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox( ex.toString(), "Database Error");
            return;
            //  return;
        }

        // 

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JComboBox<String> yr;
    // End of variables declaration//GEN-END:variables
}
