/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

//import static examples.NewJFrame2.pst;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static kiwacoe.Expenses_Capture.zstat;




//import static majiApp.Payments_capture.zyr;
//import static majiApp.Payments_capture.pst2;
//import static majiApp.Payments_BList.zstat;
//import static majiApp.Payments_capture.sql;
//import static majiApp.Payments_capture.zmon;

/**
 *
 * @author user
 */
public class Kins extends javax.swing.JFrame {
 static ResultSet rs = null;
     static ResultSet rs2 = null;
     static ResultSet rs3 = null;
    static String mx, sql,xseq;
    public int x = 0,r=0;
    static PreparedStatement pst = null;
      static PreparedStatement pst2 = null;
       static PreparedStatement pst3 = null;
    //xmembid+"','"+xnam+"',"+xamt+",'"+xtyp+"','"+xcomm+"','"+xyr+"','"+xmon+"
     public String xnam,xamt,xcomm,xtyp,xmembid,xrdate;
     static String zyr,zmon,ztyp,zfind,zstat;
     public static String zmembid,znam;
     int ff=0;
      int cnt=0;
     double tamt=0;
     public Connection conn=DBconnect.ConnecrDb();
    /**
     * Creates new form NewJDialog
     */
    public Kins(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
        
     try {
         rel=Combos.nkins(rel);
     } catch (SQLException ex) {
         Logger.getLogger(Kins.class.getName()).log(Level.SEVERE, null, ex);
     }
         rel.setSelectedItem("");
        jTable1=SetTable.data(jTable1);
         jButton3.setText("Add");
     //   zmon = Shares_List.zmon;
     //   zyr = Shares_List.zyr;
     //  ztyp = Shares_List.ztyp;
      //  zreg = Readings_BList.zreg;
      //  zstat = Shares_List.zstat;
         doread();
     //   jLabel7.setText("Year:  " + zyr + "    Month: " + zmon  + "   Type:  " + ztyp+"  Status:  "+zstat);
    //  jLabel7.setText("Year:  " + zyr + "    Month: " + zmon  +"  Status:  "+zstat);
       seq.setVisible(false);
   //    nam.setEditable(false);
       
         ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String muserid = null;
                String mtyp = null;
                String mnam = null;
                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();
                int row = jTable1.getSelectedRow();
                int col = 1; // ID is the first Column
                
              if (row>-1)
                {    
                seq.setText(jTable1.getValueAt(row, 0).toString());
           //      membid.setText(jTable1.getValueAt(row, 1).toString());
               nam.setText(jTable1.getValueAt(row, 1).toString());
                idno.setText(jTable1.getValueAt(row, 2).toString());
                 telno.setText(jTable1.getValueAt(row, 3).toString());
                  padd.setText(jTable1.getValueAt(row, 4).toString());
                   email.setText(jTable1.getValueAt(row, 5).toString());
                   rel.setSelectedItem(jTable1.getValueAt(row, 6).toString());
              
          
                   //  jButton3.setEnabled(true);
                      jButton3.setText("Save");
           //     }
                 
              
                
                 
                
            
                }
            }

        });
        
       
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        cmt.setVisible(false);
     //   updatetots();
      
      // poputate_fields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        padd = new javax.swing.JTextField();
        seq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        rel = new javax.swing.JComboBox<>();
        telno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        cmt.setFocusable(false);

        jLabel5.setText("Postal Address");

        jButton1.setText(">>");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        jLabel6.setText("Tel . No");

        padd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paddActionPerformed(evt);
            }
        });

        seq.setText("jTextField1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Relationship");

        telno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnoActionPerformed(evt);
            }
        });

        jLabel9.setText("ID No.");

        jLabel10.setText("Email Address");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jButton5.setText("New");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton2)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton3)
                .addGap(141, 141, 141)
                .addComponent(seq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(padd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(cmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(padd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(seq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

          try{
            if (x == 0) {
                open();
            }

            if(!rs3.isLast())
            {
                rs3.next();
                int cnt= rs3.getRow();
                int cmm=  cntt();
                cmt.setText(Integer.toString( cnt)+" of "+ Integer.toString( cmm));
                loaddata();
            }else
            {
                rs3.last();
                //   msbbox.show( Alert.AlertType.ERROR,"End of File", "titleBar",  "Header");
                return;
            }
        } catch (SQLException ex) {
            //      Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 public void doread()
{
    // String = mon.getSelectedItem().toString();
    //  String syr = yr.getSelectedItem().toString();
    //  String smon = String.format("%02d", mon.getSelectedIndex() + 1);

    sql = " select * from  kins where membid='" + zmembid + "'";
    //    System.
    //   MessageBox.infoBox(sql, "dffd");

    System.out.println(sql);
    DefaultTableModel model = new DefaultTableModel();
    // jTable1 hh;
    jTable1.setModel(model);

    model.addColumn("Rec ID");
  //  model.addColumn("Member ID");
    model.addColumn("Name");
    model.addColumn("ID No");
    model.addColumn("Tel No");
    model.addColumn("P Address");
    model.addColumn("Email");
    model.addColumn("Rel.Ship");
//    jTable1.getColumnModel().getColumn(0).setMinWidth(0);

    //   model.addColumn("2 Name");
    Connection conn = DBconnect.ConnecrDb();

    try {
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        // rs.first();
        int p = 0;
        while (rs.next()) {
            //  readdata();
            cnt = cnt + 1;
         //   tamt = tamt + Double.parseDouble(rs.getString("amt"));
            model.insertRow(p, new Object[]{
                rs.getString("kinid"),
               rs.getString("nam"),
                  rs.getString("idno"),
                    rs.getString("telno"),
                      rs.getString("paddr"),
                        rs.getString("email"),
                          rs.getString("relship"),
              //  rs.getString("nam"),
               });
        }
    } catch (SQLException ex) {
        Logger.getLogger(UsersLIst.class.getName()).log(Level.SEVERE, null, ex);
    }

 //   lcnt.setText("Record Count = " + Integer.toString(cnt));
 //   ltot.setText("Total Amount = " + Format_amt.format(Double.toString(tamt)));

    //    jTable1.removeColumn(jTable1.getColumnModel().getColumn(0)); 
    jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ALL_COLUMNS);
 //    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
    //  jTable1.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
  //  jTable1.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
   
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  try {
            if (x == 0) {
                open();
            }

            if (!rs3.isFirst()) {
                rs3.previous();
                int cnt= rs3.getRow();

                int cmm=  cntt();
                cmt.setText(Integer.toString( cnt)+" of "+ Integer.toString( cmm)  );
                // String tmembid = rs.getString("membid");  //+"\n";
                loaddata();
            } else {
                // msbbox.show(Alert.AlertType.ERROR, "End of File", "titleBar", "Header");
                rs3.first();
                loaddata();
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
           JTextField nn[] = { nam,idno,padd,telno,email};
   //    JComboBox zz[] = {typ};
        int jj = Validate_Empty_Fields.validate_textfields(nn);
      //  int yy = Validate_Empty_Fields.validate_comboboxes(zz);
        if (jj == 1 ) {
            return;
        }
        
        String mm=jButton3.getText().toString();
         getdata();    
        if (mm.equals("Save"))
        {
            performSave();
        }else
        {
            performAdd();
        }
        doread();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       // NewJFrame2 frame = new NewJFrame2();

       // frame.dispose();
        Kins.this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed
public void  updatetots()
{
   //   try {
   //     String[] qq= BatchTotals.yrmontyp(zyr, zmon, ztyp, "shbatches", "shares");
   //      cmt.setText(" Records="+qq[0]+"    Total Amount="+qq[1]);
   //  } catch (SQLException ex) {
   //      Logger.getLogger(Shares_Capture.class.getName()).log(Level.SEVERE, null, ex);
   //  }
    try {
              PreparedStatement pst7 = null; 
              Connection connx=DBconnect.ConnecrDb();
              String sql4="update shbatches set recs="+cnt+",tot="+tamt+" where CONCAT(yr,mon,typ)='"+zyr+zmon+ztyp+"'";
              System.out.print(sql4);
            //  MessageBox.infoBox(sql4, zstat);
              pst7=connx.prepareStatement(sql4);
              pst7.executeUpdate(sql4);
             
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Shares_Capture.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox(ex.toString(), "New  Batch");
              return;
         //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
          }
}
    private void idnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnoActionPerformed

    private void paddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paddActionPerformed

    private void telnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telnoActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        nam.setText("");
         idno.setText("");
          telno.setText("");
           padd.setText("");
            email.setText("");
             rel.setSelectedItem("");
              jButton3.setText("Add");
             nam.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

   public void populate_data() throws SQLException
{
    /*
    String sql = "SELECT *  from kins where membid='" + membid.getText().toString() + "'";
    //Connection conn = DBconnect.ConnecrDb();
    System.out.println(sql);
    pst2 = conn.prepareStatement(sql);
    rs2 = pst2.executeQuery();
    // metno="Nil";
    // metsz="Nil";
    while (rs2.next()) {
        nam.setText(rs2.getString("nam"));

        amt.requestFocus();

    }
  */
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments_capture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payments_capture dialog = new Payments_capture(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
               
              //  dialog.setModal(true);
              //  dialog.setSize(400, 400);
                dialog.setLocationRelativeTo(null);
                 dialog.setTitle("Shares");
                 dialog.setResizable(false);
                dialog.setVisible(true);
            }
        });
    }
public void open() throws SQLException
{
    String        sql = "SELECT * from shares where yr='" + zyr + "' and mon='" + zmon + "' and typ='"+ztyp+"' order by seq";
  //  Connection conn = DBconnect.ConnecrDb();
    pst3 = conn.prepareStatement(sql);
    rs3 = pst3.executeQuery();
    x = 1;    
    int cnt= cntt();
   cmt.setText(Integer.toString( cnt));
}
public void loaddata()
{
      try {
          
       
//        membid.setText(rs3.getString("membid"));

        nam.setText(rs3.getString("nam"));
  //      rdate.setText(Format_date.dmy(rs3.getString("rdate")));
        idno.setText(rs3.getString("amt"));
      //  pread.setText(rs3.getString("pread"));
      //  cread.setText(rs3.getString("cread"));
        padd.setText(rs3.getString("comm"));
         seq.setText(rs3.getString("seq"));
         //  typ.setSelectedItem(rs3.getString("typ"));
        jButton3.setText("Save");

    } catch (SQLException ex) {
        Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
       MessageBox.infoBox(ex.toString(), "dd");
    }

}
public void performAdd()  
{
    
    
  //   String dd=xrdate.substring(0,2);
  //   String ddx=xrdate.substring(0,5);
 //    String mm=ddx.substring(3);
 //   
 //    String yy=xrdate.substring(6);
 //    xrdate=yy+"/"+ mm+"/"+dd;
 // MessageBox.infoBox(xrdate, "sss");// membid,nam,typ,grp,comm,yr,mon,reg,cread,pread,cdate,ctime                                     
 
     
       sql = "insert into  kins (membid,nam,idno,telno,paddr,email,relship,sdate,stime)"
               + " values('"
               + zmembid+"','"
               +nam.getText().toString()+"','"
               +idno.getText().toString()+"',"
               +telno.getText().toString()+",'"
               +padd.getText().toString()+"','"
               +email.getText().toString()+"','"
               +rel.getSelectedItem().toString()+"'"
               +",CURDATE(),CURTIME())";  
    //   Connection conn=DBconnect.ConnecrDb();
         System.out.println(sql);
          try {
             
              
              pst2=conn.prepareStatement(sql);
              pst2.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Shares_Capture.class.getName()).log(Level.SEVERE, null, ex);
            //   msbbox.show(Alert.AlertType.ERROR, ex.toString(),"insertrec Method" ,"Database Error");
            MessageBox.infoBox(ex.toString(), "Error");   
            return;
          }
          doread();
       nam.setText("");
         idno.setText("");
          telno.setText("");
           padd.setText("");
            email.setText("");
             rel.setSelectedItem("");
              jButton3.setText("Add");
             nam.requestFocus();
    
}
 public void poputate_fields() {
     //   Connection conn = DBconnect.ConnecrDb();

        sql = "SELECT * from shares where yr='" + zyr + "' and mon='" + zmon  + "' and typ='" + ztyp + "'";

        try {
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            rs.first();
          //  rdate.setText(rs.getString("rdate"));
        //   rdate.setText(Format_date.dmy(rs.getString("rdate")));
        //    membid.setText(rs.getString("membid"));
            nam.setText(rs.getString("nam"));

            idno.setText(rs.getString("amt"));
          //   typ.setSelectedItem(rs.getString("typ"));

        } catch (SQLException ex) {
            Logger.getLogger(UsersLIst.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public void performSave()
{
  //  xrdate=rdate.getText().toString();
 //   String dd=xrdate.substring(0,2);
//     String ddx=xrdate.substring(0,5);
//     String mm=ddx.substring(3);
    //
   //  String yy=xrdate.substring(6);
  //   xrdate=yy+"/"+ mm+"/"+dd;
 //  String gamt= idno.getText().toString();
 //   double kamt=Double.parseDouble(gamt);
   
    
    
     sql = " update kins set "
        //    + "rdate='" + xrdate + "'"
            + "nam='" + nam.getText().toString() + "'"
         //    + ",typ='" + nam.getText().toString() + "'"
           + ",membid='" + zmembid + "'"
               + ",paddr='" + padd.getText().toString() + "'"
            + ",relship='" + rel.getSelectedItem().toString() + "'"
               + ",telno='" + telno.getText().toString() + "'"
               + ",email='" + email.getText().toString() + "'"
               + ",idno='" + idno.getText().toString() + "'"
       
          //  + ",amt=" + gamt  + ""
     
            + //  ",paddr='" + xpaddr +"'"+
            "  where kinid=" + seq.getText().toString() + "";
       
    System.out.println(sql+"@#@@@@@@@");
     
   //   msbbox.show(Alert.AlertType.ERROR, sql,"insertrec Method" ,"Database Error");
       
         System.out.println(sql);
          try {
              pst2=conn.prepareStatement(sql);
              pst2.executeUpdate(sql);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Payments_capture.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox("Record Update Error", "Error");
              System.out.print(sql);
             //msbbox.show(Alert.AlertType.ERROR, ex.toString(),"insertrec Method" ,"Database Error");
              return;
          }
       
     try {
         refresh_recordset(); //msbbox.show(Alert.AlertType.ERROR, ex.toString(),"insertrec Method" ,"Database Error");
     } catch (SQLException ex) {
         Logger.getLogger(Expenses_Capture.class.getName()).log(Level.SEVERE, null, ex);
     }
}
public void refresh_recordset() throws SQLException 
{
  /*  
    int zz=rs3.getRow();
     String        sql = "SELECT * from shares where yr='" + zyr + "' and mon='" + zmon + "' and typ='" + ztyp + "'";
  //  Connection conn = DBconnect.ConnecrDb();
    pst3 = conn.prepareStatement(sql);
    rs3 = pst3.executeQuery();
    x = 1;    
    int cnt= cntt();
   cmt.setText(Integer.toString( cnt));
   
  rs3.absolute(zz);
  loaddata();
 */
}
public void getdata()
{
  
  //  xmembid = membid.getText().toString();
    xnam = nam.getText().toString();
  //  xrdate = rdate.getText().toString();
    xamt = idno.getText().toString();
    xcomm = padd.getText().toString();
 xtyp = rel.getSelectedItem().toString();
 /*
    String mdate[] = xrdate.split("/");
    String d = mdate[0];
    String m = mdate[1];
    String y = mdate[2];
    xrdate = y + "-" + m + "-" + d;
    //  xtyp = typ.getSelectedItem().toString();
   */
}
public int cntt() throws SQLException
{
    
    String sql = "SELECT count(*) as cnt from shares where yr='" + zyr + "' and mon='" + zmon + "' ";
  //  Connection conn = DBconnect.ConnecrDb();
    System.out.println(sql);
    pst2 = conn.prepareStatement(sql);
    rs2 = pst2.executeQuery();
    rs2.next();
    int cnt= rs2.getInt("cnt");
    return cnt;
}
public Date convertToDate(String receivedDate) throws ParseException{
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        Date date = formatter.parse(receivedDate);
        return date;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmt;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField padd;
    private javax.swing.JComboBox<String> rel;
    private javax.swing.JTextField seq;
    private javax.swing.JTextField telno;
    // End of variables declaration//GEN-END:variables
}
