/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

//import static majiApp.Readings_BList.zyr;


/**
 *
 * @author user
 */
public class LoansNew_List extends javax.swing.JFrame {
    DefaultTableModel testlist = new DefaultTableModel();
    ResultSet rs = null;
    public String mx, sql;
    HashMap hm = null;
    ResultSet rs22 = null;
    ResultSet rs2 = null;
     Connection conn = DBconnect.ConnecrDb();
    PreparedStatement pst = null;
    PreparedStatement pst22 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst32 = null;
    public String xuserid, xnam, xpass, xtyp;
    static String zyr, zmon, ztyp, zstat;
    public Connection connz = null;
    //  static String muserid,mnam,mtyp; 
    //   public static  ListSelectionModel cellSelectionModel ;
    /**
     * Creates new form UsersLIst
     * 
     * 
     */
         static JTable table;
    public LoansNew_List() {
    //  table=jTable1;
        initComponents();
         jMenu4.setVisible(false);
        jTable1=SetTable.data(jTable1);
          String qym[] = GetMonth.set_yr_mon();
        mon.setSelectedItem(qym[0]);
        yr.setSelectedItem(qym[1]);
        jButton1.setVisible(false);
              ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String muserid = null;
                String mtyp = null;
                String mnam = null;
                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();
                int row = jTable1.getSelectedRow();
                int col = 1; // ID is the first Column
                if(row>-1)
                { 
                zyr = jTable1.getValueAt(row, 0).toString();
                zmon = jTable1.getValueAt(row, 1).toString();
              //  ztyp = jTable1.getValueAt(row, 2).toString();
                zstat = jTable1.getValueAt(row, 4).toString();
                }
                System.out.println("Selected: " + mtyp);
            }

        });
     doread(); 

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        yr = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mon = new javax.swing.JComboBox<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Open Batch");
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Print Batch");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Month");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        yr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        yr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yrFocusGained(evt);
            }
        });
        yr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrActionPerformed(evt);
            }
        });

        jLabel1.setText("Year");

        jLabel2.setText("Month");

        jButton5.setText("Post  Batch");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        mon.setToolTipText("");
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });

        jMenu3.setText("File");
        jMenu3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenu3FocusGained(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Batches");

        jMenuItem2.setText("Add Batch");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(53, 53, 53)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row<0)
        {
           MessageBox.infoBox("No Batch Selected", "Open Batch");
           return;
        }
        
        LoansNew_Capture dd=new LoansNew_Capture(this,true);
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
               dd.setResizable(false);
                dd.setDefaultCloseOperation(dd.DO_NOTHING_ON_CLOSE);
          dd.setTitle("New Loans Capture");
          dd.setVisible(true);
           this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // UsersLisr.e
        LoansNew_List.this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       //  this.setCursor(cursor_typ.busy());
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            MessageBox.infoBox("No Batch Selected", "Open Batch");
            return;
        }
        this.setCursor(cursor_typ.busy());
        hm = new HashMap();
        hm.put("yr", zyr);
        hm.put("mon", zmon);
        hm.put("title", "New Loans For : " + GetMonth.format(zmon) + "  , " + zyr);
        String filename = "reportloans.jrxml";
        String title = "New Loans For : " + GetMonth.format(zmon) + "  , " + zyr;
        RunReports.preview(filename, hm, title);
        // Insert a row at position p
        // int p = 1;
        // model.insertRow(p, new Object[] { "r3" });
        this.setCursor(cursor_typ.notbusy());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //  MessageBox.infoBox("sdffdfsd", "dfdfgg");
        LoansNew_B_Add dd=new LoansNew_B_Add(this,true);
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
               dd.setResizable(false);
          dd.setTitle("Add New Loans Batch");
          dd.setVisible(true);
         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void yrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrActionPerformed
        // TODO add your handling code here:
       doread();
    }//GEN-LAST:event_yrActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String ans=Confirm.YesNo("Are You Sure?", "Post Batch");
          if (ans.equals("N"))
          {
              return;
          }
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            MessageBox.infoBox("No Batch Selected", "Post Batch");
            return;
        }
        if (zstat.equals("Posted")) {
            MessageBox.infoBox("Batch Already Posted", "Post Batch");
            return;
        }
        
         try {
            // TODO add your handling code here:
            if (Validate_period.validate(zyr, zmon) < 1) {
                MessageBox.infoBox("Cant Post,Period not open!!", "Post Batch");
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoansNew_List.class.getName()).log(Level.SEVERE, null, ex);
        }
       
             try {
                  this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                 postbatch(zyr,zmon);
                 doread();
                 this.setCursor(Cursor.getDefaultCursor());
             } catch (SQLException ex) {
                 Logger.getLogger(LoansNew_List.class.getName()).log(Level.SEVERE, null, ex);
             }
        
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
    try {
        // TODO add your handling code here:
        update_batch();
    } catch (SQLException ex) {
        Logger.getLogger(LoansNew_List.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2FocusGained

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LoansNew_List.this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenu3FocusGained
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_jMenu3FocusGained

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        LoansNew_B_Add dd=new LoansNew_B_Add(this,true);
          // dd.setModal(true);
              //  dialog.setSize(400, 400);
                dd.setLocationRelativeTo(null);
                 dd.setDefaultCloseOperation(dd.DO_NOTHING_ON_CLOSE);
               // dd.setExtendedState(dd.MAXIMIZED_BOTH);
               dd.setResizable(false);
          dd.setTitle("Add New Loans Batch");
          dd.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void yrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yrFocusGained
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_yrFocusGained

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
        doread();
    }//GEN-LAST:event_monActionPerformed
  public void update_batch() throws SQLException
  {
       String syr = yr.getSelectedItem().toString();
      String smon = String.format("%02d", mon.getSelectedIndex() + 1);
      Connection conn = DBconnect.ConnecrDb();
      
      String msql="select * from nwlbatches where CONCAT(yr,mon)='"+syr+smon+"'";
      PreparedStatement pst99 = conn.prepareStatement(msql);
        System.out.print(msql);
      ResultSet rs1 = pst99.executeQuery();
     //  rs = pst.executeQuery();
      while (rs1.next()) {
        String  btyp = rs1.getString("typ");
     

      String sql = "SELECT count(*) as cnt from loans where CONCAT(yr,mon)='" + syr + smon + "'";

      int bb = 0;
      pst = conn.prepareStatement(sql);
      System.out.print(sql);
      rs = pst.executeQuery();
      while (rs.next()) {
          bb = rs.getInt("cnt");
      }
      String sql2 = " update nwlbatches set recs=" + Double.toString(bb)+" where CONCAT(yr,mon,typ)='" + syr + smon + btyp + "'";
      pst = conn.prepareStatement(sql2);
      pst.executeUpdate(sql2);
      
       }
  }
     public void update_batch_stat(String ssql3)
   {
       try {
           pst32 = connz.prepareStatement(ssql3);
           pst32.executeUpdate(ssql3);
           //    rs= pst.executeQuery();
       } catch (SQLException ex) {
           Logger.getLogger(Payments_BList.class.getName()).log(Level.SEVERE, null, ex);
           MessageBox.infoBox(ex.toString(), "Update Batch Status Method");
           return;
       }
   }
   public void postbatch(String zyr,String zmon) throws SQLException
{
    
   
        //String sx = membid.getText().toString();
    sql = "SELECT * from loans where yr='" + zyr + "' and mon='" + zmon + "' order by accno ";
    Connection connx = DBconnect.ConnecrDb();
    pst2 = connx.prepareStatement(sql);
    System.out.println(sql);
    rs2 = pst2.executeQuery();
   // rs2.first();
    while (rs2.next()) {
       // MessageBox.infoBox("here", zstat);
       readbatch(zyr, zmon,rs2);
    }
    Close_batch.close(zyr, zmon, "nwlbatches");
    MessageBox.infoBox("Posting Done!!", "Post Batch");
    }

 public void readbatch(String hyr,String hmon,ResultSet rrs) throws SQLException {
     //accno 	loanid 	typ 	yr 	mon 	bf 	intr 	cf 	nam   
     //    MessageBox.infoBox("here", zstat);
     System.out.print("\t" + "========amt==============" + "\n");
     String amt = rrs.getString("amt");
     System.out.print("\t" + amt + "\n");
     String fee = rrs.getString("fee");
     String membid = rrs.getString("membid");
     System.out.print("\t" + membid + "\n");
     //  String nam = rrs.getString("nam");
     String dat = rrs.getString("cdate");
     System.out.print("\t" + dat + "\n");
     String pseq = rrs.getString("accno");
     System.out.print("\t" + pseq + "\n");
     String typ = rrs.getString("typ");
     System.out.print("\t" + typ + "\n");
     String loanid = rrs.getString("loanid");
     System.out.print("\t" + loanid + "\n");
     System.out.print("\t" + "===========loanid===========" + "\n");
     String soc = "New Loans";
     String suffix = membid;
     String descr = "New Loans";

     String accno = "0000";
     //  MessageBox.infoBox(pseq, descr);
     System.out.print("\t" + pseq + "\n");

     //POst Principal Amount     
   switch (loanid) {
         case "003":
             accno = "1201";
             break;
         case "001":
             accno = "1202";
             break;
         case "002":
             accno = "1203";
             break;
         case "004":
             accno = "1204";
             break;
     }
    String dr = amt;
     String cr = "0";
     insert_rec(accno, soc, descr, suffix, dr, cr, hyr, hmon, dat, pseq);//post dr
     
     accno = "1101";
     cr = amt;
     dr = "0";
     insert_rec(accno,soc,descr,suffix,dr,cr,hyr,hmon,dat,pseq);//post cr
     
  //end of primcipal post   
     // POST loan application fee
          cr = fee;
      dr = "0";
      switch (loanid) {
         case "003":
             accno = "3101";
             break;
         case "001":
             accno = "3102";
             break;
         case "002":
             accno = "3103";
             break;
         case "004":
             accno = "3104";
             break;
     }
  //   insert_rec(accno, soc, descr, suffix, dr, cr, hyr, hmon, dat, pseq);//post dr
     
     accno = "1101";
     dr = fee;
     cr = "0";
  //    insert_rec(accno,soc,descr,suffix,dr,cr,hyr,hmon,dat,pseq);//post cr
  
     
     //end of application fee
    }
    
    public void insert_rec(String accno,String soc,String descr,String suffix,String dr,String cr,String hyr,String hmon,String dat,String pseq)
    {      
         
        sql = "insert into gl (accno,soc,descr,suffix,dr,cr,yr,mon,dat,pseq,docno,pdate,ptime) values("
                + accno
                + ",'" + soc + "'"
                + ",'" + descr + "'"
                + ",'" + suffix + "'"
                + "," + dr + ""
                + "," + cr + ""
                + ",'" + hyr + "'"
                + ",'" + hmon + "'"
                + ",'" + dat + "'"
                + "," + pseq + ""
                  + ",'"+pseq+"'"
                + ",CURDATE(),CURTIME())";
        //     msbbox.show(Alert.AlertType.ERROR, sql, "Save Method", "Database Error");
       
        System.out.println(sql);
        try {

            pst22 = conn.prepareStatement(sql);
            pst22.executeUpdate(sql);
            //    rs= pst.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(LoansNew_List.class.getName()).log(Level.SEVERE, null, ex);
            MessageBox.infoBox( ex.toString(), "Database Error");
            //  return;
        }

        // msbbox.show(Alert.AlertType.ERROR, "New record saved successfully", "New Record", "ffff");

    }
     public void doread()
{
  //  if (jTable1.getSelectedRow() > 0) {
        try {
            // String = mon.getSelectedItem().toString();

            update_batch();
        } catch (SQLException ex) {
            Logger.getLogger(LoansNew_List.class.getName()).log(Level.SEVERE, null, ex);
            MessageBox.infoBox("Batch Update Error", "Error");
    //    }
    }
    String syr = yr.getSelectedItem().toString();
    String smon = String.format("%02d", mon.getSelectedIndex() + 1);
  
    sql = " select * from nwlbatches where yr='" + syr + "' and mon='" + smon + "' ";
    //    System.
    //   MessageBox.infoBox(sql, "dffd");

    System.out.println(sql);
    DefaultTableModel model = new DefaultTableModel();
    // jTable1 hh;
    jTable1.setModel(model);
    model.addColumn("Year");
    model.addColumn("Month");
    // model.addColumn("Region");
   // model.addColumn("Loan Type");
    model.addColumn("No of Recs");

    model.addColumn("Total Amount");
    model.addColumn("stat");
    // model.
    // Create the first row
    Connection conn = DBconnect.ConnecrDb();

    //  String sql = "SELECT * from users ";
    try {
        pst = conn.prepareStatement(sql);

        rs = pst.executeQuery();
        // rs.first();
        int p = 0;
        String byr = "";
        String bmon = "";
        //  String btyp = "";
        //  String bdate = "";
        String bstat = "";
        String brecs = "";
        String btot = "";
        String btyp = "";

        while (rs.next()) {
            //  readdata();
            byr = rs.getString("yr");
            bmon = rs.getString("mon");
            //   breg = rs.getString("reg");
            //    btyp = rs.getString("typ");
            btot = rs.getString("tot");
            brecs = rs.getString("recs");
       //     btyp = rs.getString("typ");
            bstat = rs.getString("stat");
            model.insertRow(p, new Object[]{byr, bmon,  brecs, btot, bstat});
             jTable1.changeSelection(0, 0, false, false);
        }
    } catch (SQLException ex) {
        Logger.getLogger(UsersLIst.class.getName()).log(Level.SEVERE, null, ex);
    }
        jTable1.setShowGrid(true); 

}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JComboBox<String> yr;
    // End of variables declaration//GEN-END:variables
}
