/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Members_add extends javax.swing.JFrame {
     public String xreg,xmembid,xnam,xgrp,xcat,xmetno,xmetsz,xidno,xtelno,xpaddr,xemail,xplotno;
      ResultSet rs = null;
          public String mx,sql,xtoe,xpayid,xtown,xbnch,xsamt,xstat,xwel,xauto;

        PreparedStatement pst = null;
        static String pind,zmembid;
        int cnt=0;
         public int x = 0, r = 0;
     /**
     * Creates new form saccodb_add
     */
    public Members_add() {
        initComponents();
        
           //  town=Combos.locs(town);
        
        
           //  toe=Combos.cats(toe);
         try {
                bnch=Combos.bnchs(bnch);
            } catch (SQLException ex) {
                Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
            }
        ok.setText(pind);
        if(pind.equals("Add"))
        {
            try { 
               String id=  get_next_no();
               membid.setText(id);
            } catch (SQLException ex) {
                Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }else
        {
        poputate_fields();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        town = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        membid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        toe = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        idno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        payid = new javax.swing.JTextField();
        paddr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        damt = new javax.swing.JTextField();
        stat = new javax.swing.JCheckBox();
        wel = new javax.swing.JCheckBox();
        bnch = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        rdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        auto = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Current Region*");

        town.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "n/a", "Bungoma", "Chwele", "Kimilili", "Kitale", "Webuye" }));
        town.setToolTipText("");
        town.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townActionPerformed(evt);
            }
        });

        jLabel4.setText("Member ID*");

        membid.setEditable(false);
        membid.setFocusable(false);

        jLabel5.setText("Name*");

        jLabel7.setText("Terms of Service");

        toe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Casual", "Contract", "Permanent" }));
        toe.setToolTipText("");

        jLabel11.setText("ID  Number*");

        jLabel12.setText("Tel. Number");

        jLabel13.setText("Start Date");

        jLabel14.setText("Email Address");

        ok.setText("Save");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Bank Acc No");

        paddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paddrActionPerformed(evt);
            }
        });

        jLabel3.setText("Bank Branch");

        jLabel6.setText("Deposit Amount");

        stat.setText("Active");

        wel.setText("Welfare Member");

        bnch.setToolTipText("");

        jButton6.setText("#");
        jButton6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton6FocusGained(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        rdate.setEditable(false);

        jLabel15.setText("Postal Address");

        auto.setText(" Auto Deduct");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(town, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel11))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel15)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paddr, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(membid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel13)))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(damt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(auto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(352, 352, 352)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(membid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(town, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(toe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(damt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(bnch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(payid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(paddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stat)
                    .addComponent(wel)
                    .addComponent(auto))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok)
                    .addComponent(jButton2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Members_add.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        JTextField nn[] = { membid,nam,payid,idno,telno,email};
        JComboBox zz[] = {town,toe,bnch};
        int jj = Validate_Empty_Fields.validate_textfields(nn);
        int yy = Validate_Empty_Fields.validate_comboboxes(zz);
        if (jj == 1 || yy == 1) {
            return;
        }
        
        
        getdata();   
        if(ok.getText().toString().equals("Add"))
        {
            do_add();
        }else
        {
            do_edit();
        }
 //  msbbox.show(Alert.AlertType.ERROR, "New record saved successfully","New Record" ,"ffff");       
   // Members_listController zn = new Members_listController();
  
    }//GEN-LAST:event_okActionPerformed

    private void townActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_townActionPerformed

    private void paddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paddrActionPerformed

    private void jButton6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton6FocusGained
        // TODO add your handling code here:
        if (r ==1 && Kalenda.gdat.length()>0) {
            r=0;
            rdate.setText( Kalenda.gdat);
           // accno.requestFocus();
        }else
        {
            r=0;
        }
    }//GEN-LAST:event_jButton6FocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        r=1;
        Kalenda dd=new Kalenda();
        // dd.setModal(true);
        //  dialog.setSize(400, 400);
        dd.setLocationRelativeTo(null);
        // dd.setExtendedState(dd.MAXIMIZED_BOTH);
        dd.setDefaultCloseOperation(dd.DO_NOTHING_ON_CLOSE);
         dd.getContentPane().setBackground(Color.decode("123130040"));
        dd.setResizable(false);
        dd.setTitle("Calender");
        dd.setVisible(true);

        //  MessageBox.infoBox(Kalenda.gdat, user);
        //  this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
   public String  get_next_no() throws SQLException 
   {
       int x=0;
    
            Connection conn =DBconnect.ConnecrDb();   
     
           sql = "SELECT count(*) as cnt  from saccodb ";

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            while (rs.next())
            {
              x=rs.getInt("cnt");  
                
            }
            x=x+1;
            String id=Integer.toString(x);
            if(id.length()==1)
            {
              id="00"+id;  
            }
             if(id.length()==2)
            {
              id="0"+id;  
            }
      return id;
   }
    
    public void do_add() {

        Connection conn = DBconnect.ConnecrDb();
        sql = "insert into  saccodb (town,membid,nam,payid,toe,idno,telno,paddr,email,sdate,stime,bnch,samt,stat,wel,auto,rdate) values"
                + "('" + xtown + "','" + xmembid + "','" + xnam + "','" + xpayid + "','"
                + xtoe + "','" + xidno + "','" + xtelno + "','"
                + xpaddr + "','"
                + xemail
                + "',CURDATE(),CURTIME(),'" + xbnch + "'," + xsamt + ",'" + xstat + "','" + xwel
                   + "', '" + xauto
                + "', '" + rdate.getText().toString()
                + "')";

        System.out.println(sql);
        try {

            pst = conn.prepareStatement(sql);
            pst.executeUpdate(sql);
            //    rs= pst.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Users_add.class.getName()).log(Level.SEVERE, null, ex);
            MessageBox.infoBox(ex.toString(), "Add Customer");
            return;
            //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
        }
        membid.setText("");
        nam.setText("");
        town.setSelectedItem("");
        toe.setSelectedItem("");
        idno.setText("");
        email.setText("");
        paddr.setText("");

        payid.setText("");
        telno.setText("");
        damt.setText("");
        stat.setText("");
        wel.setText("");
        auto.setText("");
        rdate.setText("");
        bnch.setSelectedItem("");
        String id;
        try {
            id = get_next_no();
            membid.setText(id);
        } catch (SQLException ex) {
            Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
        }
        nam.requestFocus();
        // MessageBox.infoBox("Customer " + pind + "ed Successfully", pind + " Customer");
    }
public void do_edit()
{
    Connection conn = DBconnect.ConnecrDb();
    sql = " update saccodb set "
            + //    "membid='" + xmembid +"'"+
            "nam='" + xnam + "'"
            + ",payid='" + xpayid + "'"
            + ",toe='" + xtoe + "'"
            + ",idno='" + xidno + "'"
            + ",telno='" + xtelno + "'"
            + ",email='" + xemail + "'"
            + ",town='" + xtown + "'"
            + ",rdate='" + rdate.getText().toString() + "'"
            //   + rdate.getText().toString() + "','" 
            + ",samt=" + xsamt + ""
            + ",paddr='" + xpaddr + "'"
            + ",bnch='" + xbnch + "'"
            + ",stat='" + xstat + "'"
              + ",auto='" + xauto + "'"
            + ",wel='" + xwel + "'"
            + "  where membid='" + zmembid + "'";
    System.out.println(sql);
    try {
        pst = conn.prepareStatement(sql);
        pst.executeUpdate(sql);
    } catch (SQLException ex) {
        Logger.getLogger(Users_add.class.getName()).log(Level.SEVERE, null, ex);
        MessageBox.infoBox(ex.toString(), "Add Member");
        return;
    }
    MessageBox.infoBox("Record " + pind + "ed Successfully", pind + " Member");
}
    public void getdata()
{
    xmembid = membid.getText().toString();
    xnam = nam.getText().toString();
    xsamt = damt.getText().toString();
    xtown = town.getSelectedItem().toString();
    xtoe = toe.getSelectedItem().toString();
    xpayid = payid.getText().toString();
//    xmetsz = metsz.getText().toString();
    xemail = email.getText().toString();
    xidno = idno.getText().toString();
    xtelno = telno.getText().toString();
    xpaddr = paddr.getText().toString();
    xbnch = bnch.getSelectedItem().toString();
    if (stat.isSelected()) {
        xstat = "1";
    } else {
        xstat = "0";
    }
    if (wel.isSelected()) {
        xwel = "1";
    } else {
        xwel = "0";
    }
    
    
     if (auto.isSelected()) {
        xauto = "1";
    } else {
        xauto = "0";
    }
   
}    
public void poputate_fields()
 {
        Connection conn = DBconnect.ConnecrDb();
        sql = "SELECT * from saccodb where membid='" + zmembid + "'";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            town.setSelectedItem(rs.getString("town"));
            membid.setText(rs.getString("membid"));
            nam.setText(rs.getString("nam"));
            damt.setText(rs.getString("samt"));
            //.setSelectedItem(rs.getString("grp"));
            toe.setSelectedItem(rs.getString("toe"));
            payid.setText(rs.getString("payid"));
            //  metsz.setText(rs.getString("metsz"));
            idno.setText(rs.getString("idno"));
            telno.setText(rs.getString("telno"));
            paddr.setText(rs.getString("paddr"));
            email.setText(rs.getString("email"));
              rdate.setText(rs.getString("rdate"));
           //  MessageBox.infoBox(rs.getString("bnch"), xtelno);
            bnch.setSelectedItem(rs.getString("bnch"));
            if (rs.getString("wel").equals("1")) {
                wel.setSelected(true);
            }
            if (rs.getString("stat").equals("1")) {
                stat.setSelected(true);
            }
            
             if (rs.getString("auto").equals("1")) {
                auto.setSelected(true);
            }
            //  MessageBox.infoBox(rs.getString("bnch").toString(), xtelno);
            //   plotno.setText(rs.getString("plotno"));

        } catch (SQLException ex) {
            Logger.getLogger(Members_add.class.getName()).log(Level.SEVERE, null, ex);
        }   
 }
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) 
{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Members_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Members_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Members_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Members_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Members_add().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox auto;
    private javax.swing.JComboBox<String> bnch;
    private javax.swing.JTextField damt;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField membid;
    private javax.swing.JTextField nam;
    private javax.swing.JButton ok;
    private javax.swing.JTextField paddr;
    private javax.swing.JTextField payid;
    private javax.swing.JTextField rdate;
    private javax.swing.JCheckBox stat;
    private javax.swing.JTextField telno;
    private javax.swing.JComboBox<String> toe;
    private javax.swing.JComboBox<String> town;
    private javax.swing.JCheckBox wel;
    // End of variables declaration//GEN-END:variables
}
