/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;

/**
 *
 * @author user
 */
public class SMS_Balances extends javax.swing.JDialog {

     ResultSet rs = null;
          public String mx,sql;

        PreparedStatement pst = null;
        public String xuserid,xnam,xpass,xtyp,xmon,xyr; 
         Connection conn = DBconnect.ConnecrDb();
    /**
     * Creates new form Users_add
     */
    public SMS_Balances(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         String qym[]=  GetMonth.set_yr_mon();
         
         
      mon.setSelectedItem(qym[0]);
      yr.setSelectedItem(qym[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mon = new javax.swing.JComboBox<>();
        yr = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        bal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Month");

        jLabel2.setText("Year");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });

        yr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        jButton3.setText("View sms Balance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mon, 0, 106, Short.MAX_VALUE)
                            .addComponent(yr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(139, 139, 139)
                                .addComponent(jButton2)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          xyr=yr.getSelectedItem().toString();
   // xmon=mon.getSelectedItem().toString();
   //  String   xxmon=mon.getSelectedItem().toString();
      xmon = String.format("%02d", mon.getSelectedIndex() + 1);  
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void createbatches() throws SQLException {
        if (Validate_batch.validate(xyr, xmon, "shbatches") == 0) {
            sql = "insert into  shbatches (yr,mon,recs,stat,bdate,tot,typ) "
                    + "values('" + xyr + "','" + xmon + "',0,'Open',CURDATE(),0,'N/A')";
            execute(sql);
            System.out.print(sql);
        }
        
          if (Validate_batch.validate(xyr, xmon, "adjbatches") == 0) {
            sql = "insert into  adjbatches (yr,mon,recs,stat,bdate,tot) "
                    + "values('" + xyr + "','" + xmon + "',0,'Open',CURDATE(),0)";
            execute(sql);
            System.out.print(sql);
        }
        
        
        if (Validate_batch.validate(xyr, xmon, "repbatches") == 0) {
            sql = "insert into  repbatches (yr,mon,recs,stat,bdate,tot) "
                    + "values('" + xyr + "','" + xmon + "',0,'Open',CURDATE(),0)";
            execute(sql);
            System.out.print(sql);
        }

        if (Validate_batch.validate(xyr, xmon, "nwlbatches") == 0) {

            sql = "insert into  nwlbatches (yr,mon,typ,recs,stat,bdate,tot) values('" + xyr + "','" + xmon + "','" + xtyp + "',0,'Open',CURDATE(),0)";
            execute(sql);
            System.out.print(sql);
        }

        if (Validate_batch.validate(xyr, xmon, "expbatches") == 0) {
            sql = "insert into  expbatches (yr,mon,recs,stat,bdate,tot) "
                    + "values('" + xyr + "','" + xmon + "',0,'Open',CURDATE(),0)";
            execute(sql);
            System.out.print(sql);
        }

    }
    public void execute(String sql4)
    {
         System.out.print(sql4);
        try {
             
              
              pst=conn.prepareStatement(sql4);
              pst.executeUpdate(sql4);
             //    rs= pst.executeQuery();
          } catch (SQLException ex) {
              Logger.getLogger(Users_add.class.getName()).log(Level.SEVERE, null, ex);
              MessageBox.infoBox(ex.toString(), "New  Batch");
              return;
         //     msbbox.show(Alert.AlertType.ERROR, ex.toString(),"SQL Error" ,"ffff");
          }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          SMS_Balances.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean mm =  false;
        try {
            mm =   Check_Internet.isInternetAvailable();

        } catch (IOException ex) {
            Logger.getLogger(Sms_customized.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (mm==true)
        {

        }else
        {
            MessageBox.infoBox("Npo Internet", "Check SMS Balance");
            return;
        }

        this.setCursor(cursor_typ.busy());
        try {
            // TODO add your handling code here:
            http_bal();
        } catch (IOException ex) {
            Logger.getLogger(Bills_SMS.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setCursor(cursor_typ.notbusy());
    }//GEN-LAST:event_jButton3ActionPerformed
public void http() throws IOException
 {
     
   //  String msg =   text.getText().toString();
   // msg=  msg.replace(" ", "%20");
     String yrmon=xyr+xmon;
     URL yahoo = new URL("http://localhost/ebills/kiwacoe3.php?yrmon='"+yrmon );
     System.out.println("http://localhost/ebills/kiwacoe3.php?yrmon='"+yrmon  );
     URLConnection yc = yahoo.openConnection();
     BufferedReader in = new BufferedReader(new InputStreamReader(yc.getInputStream()));
     String inputLine;
     while ((inputLine = in.readLine()) != null) //  System.out.println(inputLine);
     {
        MessageBox.infoBox(inputLine, "Feedback");
     }
     in.close();
      
 }
 public void http_bal() throws IOException
 {
     
    URL yahoo = new URL("http://localhost/ebills/sms22.php");
 //   System.out.println("http://localhost/ebills/sms20.php?yr="+xyr+"&mon="+xmon+"&reg="+xreg);    
    URLConnection yc = yahoo.openConnection();
        BufferedReader in = new BufferedReader(
                                new InputStreamReader(
                                yc.getInputStream()));
        String inputLine;
        double t=0;
        String qq="";  //Double.toString(t)
        while ((inputLine = in.readLine()) != null) 
          t=Double.parseDouble(inputLine);
          //  System.out.println(inputLine);
       //   bal.
       //  qq= Double.toString(t) ;
       //     bal.setText();
        inputLine=  Format_amt.formatx( Double.toString(t));
           bal.setText(inputLine);
          //  MessageBox.infoBox(inputLine, "Feedback");
        in.close();

 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Users_add dialog = new Users_add(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void getdata()
{
  
    xyr=yr.getSelectedItem().toString();
   // xmon=mon.getSelectedItem().toString();
   //  String   xxmon=mon.getSelectedItem().toString();
      xmon = String.format("%02d", mon.getSelectedIndex() + 1);  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JComboBox<String> yr;
    // End of variables declaration//GEN-END:variables
}
