/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiwacoe;

import java.awt.Cursor;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Properties;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingWorker;

/**
 *
 * @author user
 */
public class Statements_email_loans_1 extends javax.swing.JFrame {
     HashMap hm = null;
    ResultSet rs = null;
    public String mx, sql;
    int ff = 0,recs=0;
     ResultSet rsc = null;
     PreparedStatement pstc = null;
    PreparedStatement pst = null;
     int mnt=0;
    String host = "mail.nzoiawater.or.ke";
    String from = "kiwacoe@nzoiawater.or.ke";
     Connection conn = DBconnect.ConnecrDb();
    String filename2 = "";
    String to = "kiwacoe@nzoiawater.or.ke";
    
    Properties props = new Properties();
    String jtyp="";
   

    // Get the Session object.
    javax.mail.Session session = javax.mail.Session.getInstance(props,
            new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication("kiwacoe@nzoiawater.or.ke", "kiwacoe@2018");
        }
    });
    SwingWorker worker = new SwingWorker<Boolean, Integer>() {
        @Override
        protected Boolean doInBackground() throws Exception {
            // Background work

            // Value transmitted to done()
            return true;
        }

        @Override
        protected void process(List<Integer> chunks) {
            // Process results
        }

        @Override
        protected void done() {
            // Finish sequence
        }
    };

    /**
     * Creates new form Meter_Reading_List
     */
    public Statements_email_loans_1(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
      
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        membid = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sss = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Member ID");

        jButton3.setText("Find");
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        membid.setEditable(false);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(membid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 50, Short.MAX_VALUE))
                            .addComponent(nam)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(membid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
        // TODO add your handling code here:
        if  ( ff==0)
        {

        }else
        {

            //  MessageBox.infoBox(Find_Customer.zmembid, zstat);
            membid.setText(Find_Customer.zmembid);
            nam.setText(Find_Customer.znam);
       //     typ.setText(Find_Loan2.ztyp);

            //   typ.requestFocus();
            ff=0;

        }
    }//GEN-LAST:event_jButton3FocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ff=1;
        //  zmembid="";
        //  znam="";
        Find_Customer.zfind="Shares";
        Find_Customer dd=new Find_Customer();
        // dd.setModal(true);
        //  dialog.setSize(400, 400);
        dd.setLocationRelativeTo(null);
        // dd.setExtendedState(dd.MAXIMIZED_BOTH);
        dd.setResizable(false);
        dd.setTitle("Find Loan");
        dd.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jProgressBar1.setValue(0);
      
             
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "587");
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (membid.getText().trim().isEmpty()) {
            sql = "select loans.*,xamt from loans,paid where loans.accno=paid.accno  order by loans.accno";
        } else {
            sql = " select loans.*,xamt from loans,paid where loans.accno=paid.accno  and loans.accno=" + membid.getText().toString() + " order by loans.accno ";
        }
        if (membid.getText().trim().isEmpty()) {
            sql = "select * from saccodb";

        } else {
            sql = "select * from saccodb  where membid='" + membid.getText().toString() + "'";
        }
        
        String sql14="";
         if (membid.getText().trim().isEmpty()) {
          //  sql14 = "select count(*) cnt from loans,paid where loans.accno=paid.accno  order by loans.accno";
              sql14 = "select count(*) cnt from saccodb";
        } else {
          //  sql14 = " select count(*) cnt from loans,paid where loans.accno=paid.accno  and loans.accno=" + membid.getText().toString() + " ";
        }     sql14 = "select count(*) cnt from saccodb where membid='" + membid.getText().toString() + "'";
         try {
              recs=GetRecs.cnt(sql14);
                jProgressBar1.setMaximum(recs);
         } catch (SQLException ex) {
             Logger.getLogger(Statements_email_loans.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        System.out.println(sql);  // 

        Connection conn = DBconnect.ConnecrDb();

        //  String sql = "SELECT * from users ";
        try {
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            String qmail="";
           
            while (rs.next()) {
              
                String xnam = rs.getString("nam").toString(); // nam.getText().toString();
                String xmembid = rs.getString("membid").toString();
           //     String xtyp = rs.getString("typ").toString();
              //  qmail=get_email(rs.getString("membid").toString());
               qmail=  rs.getString("email").toString();
                if (!qmail.equals("n@a.com")) {
                //    jtyp = xtyp;
                    HashMap hm = new HashMap();
                    hm.put("membid", xmembid);
                  //  hm.put("typ", xtyp);
                    hm.put("title", "Loan Statement  : " + xnam + "  : " );
                    String filename = "reportEmail_loans_1.jrxml";
                    String title = "Loan Statement  : " + xnam + "  : " ;
                    //  RunReports.preview(filename, hm, title);
                    //   System.out.println(nam + " " + xtyp + " " );
                    //    msbbox.show(Alert.AlertType.ERROR,"Done", "SQL Error", "ffff");
                    //  MessageBox.infoBox("d:\\"+rs.getString("membid"+".pdf"), title);
                    // RunReports.preview2(filename, hm, title);
                    filename2 = "d:\\L" + rs.getString("membid") + ".pdf";
                    //to = "kiwacoe@nzoiawater.or.ke";
                    to=qmail;
                    RunReports.preview2(filename, hm, title, filename2);
                    ss(xmembid);
                   // sendemail3();
                }
            }
        
        
        } catch (SQLException ex) {
        Logger.getLogger(Statements_email.class.getName()).log(Level.SEVERE, null, ex);
        MessageBox.infoBox(ex.toString(), "Send Mail");
        return;
    }
        
        
        //   System.out.println(nam + " " + xtyp + " " );
        //    msbbox.show(Alert.AlertType.ERROR,"Done", "SQL Error", "ffff");
        this.setCursor(Cursor.getDefaultCursor());
       
        //    msbbox.show(Alert.AlertType.ERROR,"Done", "SQL Error", "ffff");
        this.setCursor(Cursor.getDefaultCursor());
        //    msbbox.show(Alert.AlertType.ERROR,"Done", "SQL Error", "ffff");
    }//GEN-LAST:event_jButton1ActionPerformed
public String get_email(String qmembid) throws SQLException
{
     String sqll = "select * from saccodb where membid='"+qmembid+"'";
       pstc = conn.prepareStatement(sqll);
       rsc = pstc.executeQuery();
      String qmail="n@a.com";
       while (rsc.next()) {
           qmail = rsc.getString("email");
          
       }
       return qmail;
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Statements_email_loans_1.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meter_Reading_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meter_Reading_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meter_Reading_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meter_Reading_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Meter_Reading_List dialog = new Meter_Reading_List(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public void pass() {
   // run(()-> sendemail3());
}

public void run(Runnable function) {
   // function.run();
}
 public void ss(String accno) {
        SwingWorker<Boolean, Void> worker = new SwingWorker<Boolean, Void>() {

            @Override

            protected Boolean doInBackground() throws Exception {

                // Simulate doing something useful.
               // for (int i = 0; i <= 100; i++) {
              
               //     Thread.sleep(1000);
                //     sss.setText("Running " + i);
                        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        sss.setText("Sending Email for Acc  No. "+accno+"...Please Wait!! ");
                        sendemail3(accno);

               // }

                // Here we can return some object of whatever type
                // we specified for the first template parameter.
                // (in this case we're auto-boxing 'true').
                return true;

            }

            // Can safely update the GUI from this method.
            protected void done() {

                boolean status;

                try {

                    // Retrieve the return value of doInBackground.
                    status = get();

                    sss.setText("Completed with status: " + status);
                    MessageBox.infoBox("Done!!", "Send Emails");
                    jProgressBar1.setValue(0);
                    sss.setText("");
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

                } catch (InterruptedException e) {

                    // This is thrown if the thread's interrupted.
                } catch (ExecutionException e) {

                    // This is thrown if we throw an exception
                    // from doInBackground.
                }

            }

        };

        worker.execute();
    }
    
public void sendemail3(String accno) {
        try {
            // Create a default MimeMessage object.
            sending();
        } catch (MessagingException e) {
            System.out.println(e.toString());
            sss.setText("Can't send email..no connection or invalid email address for accno " + accno + "  !!");
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            MessageBox.infoBox(e.toString(), to);
            sss.setText("");

            throw new RuntimeException(e);
        }
        // MessageBox.infoBox("done", " s");
}
public void sending() throws MessagingException
{
      Message message = new MimeMessage(session);
        // Set From: header field of the header.
        message.setFrom(new InternetAddress("KIWACOE"+"<"+from+">"));
        // Set To: header field of the header.
        message.setRecipients(Message.RecipientType.TO,
                InternetAddress.parse(to));
        // Set Subject: header field
        message.setSubject("Kiwacoe Loan Statement (" +jtyp+")");
        // Now set the actual message
        message.setText("Hello, this is sample for to check send "
                + "email using JavaMailAPI ");
        //  message.a
        // Send message
        //   added============================================================================
        MimeBodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setContent("Attached please find your Loan  Statement (" +jtyp+")", "text/html");
        // String filename="d:\\iTextHelloWorld.pdf";
        BodyPart AttachBodyPart = new MimeBodyPart();
        DataSource source = new FileDataSource(new File(filename2));
        AttachBodyPart.setDataHandler(new DataHandler(source));
        AttachBodyPart.setFileName("Loan Statement.pdf");
        //  AttachBodyPart.setContent(filename);
        Multipart multipart2 = new MimeMultipart();
        multipart2.addBodyPart(messageBodyPart);
        multipart2.addBodyPart(AttachBodyPart);
        // sets the multi-part as e-mail's content
        message.setContent(multipart2);
        javax.mail.Transport.send(message);
          mnt=mnt+1;
               jProgressBar1.setValue(mnt);
        System.out.println("Sent message successfully....");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField membid;
    private javax.swing.JTextField nam;
    private javax.swing.JLabel sss;
    // End of variables declaration//GEN-END:variables
}
